{{- if .Values.cleanerSuccessfulRuns.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: clean-successful-mongo-job
  labels:  {{- include "sorry-cypress-helm.labels" . | nindent 4 }}
    component: backend-recurrent-task
    padoa.fr/alert-severity: {{ .Values.cleanerSuccessfulRuns.alert_severity | default "low" }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.cleanerSuccessfulRuns.schedule }}"
  jobTemplate:
    metadata:
      labels: {{- include "sorry-cypress-helm.labels" . | nindent 8 }}
        component: backend-recurrent-task
        padoa.fr/alert-severity: {{ .Values.cleanerSuccessfulRuns.alert_severity | default "low" }}
    spec:
      backoffLimit: {{ .Values.cleanerSuccessfulRuns.backoff_limit | default 1 }}
      template:
        metadata:
          labels: {{- include "sorry-cypress-helm.labels" . | nindent 12 }}
            component: backend-recurrent-task
            padoa.fr/alert-severity: {{ .Values.cleanerSuccessfulRuns.alert_severity | default "low" }}
        spec:
          {{- if .Values.nodeSelector }}
          nodeSelector:
          {{- toYaml .Values.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if .Values.tolerations }}
          tolerations:
          {{- toYaml .Values.tolerations| nindent 12 }}
          {{- end }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "sorry-cypress-helm.serviceAccountName" . }}
          securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}-clean-mongo-job
              command: 
              - /bin/sh
              - -c
              - |
                {{- if .Values.cleanerSuccessfulRuns.dryRun }}
                echo "[INFO] Mode : Dry run"

                mongo "$MONGODB_URI"/"$MONGODB_DATABASE" --eval 'db.runs.count({"progress.groups.instances.failures" : 0, "createdAt": { $lte: new Date(ISODate().getTime() - 1000 * 3600 * 24 * "'$RETENTION_DAYS'").toISOString()}})';
                mongo "$MONGODB_URI"/"$MONGODB_DATABASE" --eval 'db.instances.count({ "results.stats.failures": 0, "results.stats.wallClockStartedAt": { $lte: new Date(ISODate().getTime() - 1000 * 3600 * 24 * "'$RETENTION_DAYS'").toISOString()} })';
                echo "[INFO] Fin du dry run"
                {{- end }}

                {{- if not .Values.cleanerSuccessfulRuns.dryRun }}

                mongo "$MONGODB_URI"/"$MONGODB_DATABASE" --eval 'db.runs.deleteMany({"progress.groups.instances.failures" : 0, "createdAt": { $lte: new Date(ISODate().getTime() - 1000 * 3600 * 24 * "'$RETENTION_DAYS'").toISOString()}})';
                mongo "$MONGODB_URI"/"$MONGODB_DATABASE" --eval 'db.instances.deleteMany({ "results.stats.failures": 0, "results.stats.wallClockStartedAt": { $lte: new Date(ISODate().getTime() - 1000 * 3600 * 24 * "'$RETENTION_DAYS'").toISOString()} })';
                

                echo "[INFO] Fin de la suppression des runs successful datant de plus de 7 jours"
                {{- end }}
              env:
                - name: MONGODB_DATABASE
                  value: "{{ .Values.mongodb.mongoDatabase }}"
                - name: MONGODB_URI
                  value: "{{ .Values.mongodb.mongoConnectionString }}"
                - name: RETENTION_DAYS
                  value: "{{ .Values.cleanerSuccessfulRuns.retention_days }}"
              resources:
                limits:
                  memory: {{ .Values.cleanerSuccessfulRuns.limit_memory | quote }}
                  cpu: {{ .Values.cleanerSuccessfulRuns.limit_cpu | quote }}
                requests:
                  memory: {{ .Values.cleanerSuccessfulRuns.request_memory | quote }}
                  cpu: {{ .Values.cleanerSuccessfulRuns.request_cpu | quote }}
              securityContext:
              {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.cleanerSuccessfulRuns.image.repository }}:{{ tpl .Values.cleanerSuccessfulRuns.image.tag . }}"
              imagePullPolicy: {{ .Values.cleanerSuccessfulRuns.image.pullPolicy }}
          restartPolicy: OnFailure
{{end}}
