apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sorry-cypress-helm.fullname" . }}-director
spec:
  replicas: {{ .Values.director.replicas }}
  selector:
    matchLabels:
      app: {{ include "sorry-cypress-helm.fullname" . }}-director
  template:
    metadata:
      name: {{ include "sorry-cypress-helm.fullname" . }}-director
      labels:
        app: {{ include "sorry-cypress-helm.fullname" . }}-director
        {{- with .Values.director.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
      {{- with .Values.director.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      nodeSelector:
        {{ toYaml .Values.director.nodeSelector | nindent 8 }}
      {{- with .Values.director.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.director.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      containers:
      - env:
        - name: DASHBOARD_URL
          value: {{ .Values.director.environmentVariables.dashboardUrl | quote }}
        - name: ALLOWED_KEYS
          value: {{ .Values.director.environmentVariables.allowedKeys }}
        - name: PORT
          value: {{ .Values.director.service.port | quote }}
        - name: EXECUTION_DRIVER
          value: {{ .Values.director.environmentVariables.executionDriver }}
	{{- if eq .Values.director.environmentVariables.executionDriver "../execution/mongo/driver" }}
        - name: MONGODB_DATABASE
          value: {{ .Values.mongodb.mongoDatabase }}
        - name: MONGODB_URI
        {{- if .Values.mongodb.mongoConnectionString }}
        {{- if or (.Values.mongodb.mongoSecretConnectionString.enableSecret) (.Values.mongodb.mongoSecretConnectionString.enableCustomSecret) }}
          valueFrom:
            secretKeyRef:
              name: {{ include "sorry-cypress-helm.fullname" . }}-mongodbsecrets
              key: MONGODB_URI
        {{- else }}
	  value: {{ .Values.mongodb.mongoConnectionString }}
	{{- end }}
	{{ else }}
          value:    "mongodb://{{ include "mongodb.hostname" . }}:{{ .Values.mongodb.service.port }}"
        {{- end }}
        {{- end }}
        - name: SCREENSHOTS_DRIVER
          value: {{ .Values.director.environmentVariables.screenshotsDriver }}
        {{- if and (not .Values.minio.enabled) (eq .Values.director.environmentVariables.screenshotsDriver "../screenshots/s3.driver") }}
        - name: S3_BUCKET
          value: {{ .Values.s3.bucketName }}
        - name: S3_REGION
          value: {{ .Values.s3.region }}
        {{- with .Values.s3.acl }}
        - name: S3_ACL
          value: {{ . }}
        {{- end }}
        {{- with .Values.s3.readUrlPrefix }}
        - name: S3_READ_URL_PREFIX
          value: {{ . | quote }}
        {{- end }}
        {{- with .Values.s3.accessKeyId }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ . }}
        {{- end }}
        {{- if .Values.s3.secretAccessKey }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "sorry-cypress-helm.fullname" . }}-s3secrets
              key: AWS_SECRET_ACCESS_KEY
        {{- end }}
        {{- end }}
        {{- if and (.Values.minio.enabled) (eq .Values.director.environmentVariables.screenshotsDriver "../screenshots/minio.driver") }}
        - name: MINIO_BUCKET
          value: {{ .Values.minio.defaultBucket.name }}
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ default (include "sorry-cypress.minio.fullname" .) .Values.minio.existingSecret }}
              key: "accesskey"
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ default (include "sorry-cypress.minio.fullname" .) .Values.minio.existingSecret }}
              key: "secretkey"
        - name: MINIO_ENDPOINT
          value: {{ .Values.minio.endpoint }}
        - name: MINIO_URL
          value: {{ .Values.minio.url }}
        - name: MINIO_PORT
          value: {{ .Values.minio.service.port | quote }}
        {{- if eq (.Values.minio.service.port | quote) (443 | quote) }}
        - name: MINIO_USESSL
          value: "true"
        {{- end }}
        {{- end }}
        - name: INACTIVITY_TIMEOUT_SECONDS
          value: {{ .Values.director.environmentVariables.inactivityTimeoutSeconds | quote }}
        image: "{{ .Values.director.image.repository }}:{{ .Values.director.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.director.image.pullPolicy }}
        name: {{ include "sorry-cypress-helm.fullname" . }}-director
        ports:
        - containerPort: {{ .Values.director.service.port }}
        resources:
          {{- toYaml .Values.director.resources | nindent 10 }}
      restartPolicy: Always
      {{- with (.Values.director.serviceAccount.name | default .Values.director.serviceAccountName) }}
      serviceAccountName: {{ . | quote }}
      {{- end }}
      volumes: null
      {{- if .Values.director.initContainers }}
      initContainers:
      {{- include "common.tplvalues.render" (dict "value" .Values.director.initContainers "context" $) | nindent 8 }}
      {{- end  }}
