apiVersion: v2
name: sorry-cypress
description: A Helm chart for Sorry Cypress
type: application
version: 1.1.0
appVersion: 1.1.1
home: https://sorry-cypress.dev/
sources:
  - https://github.com/sorry-cypress/sorry-cypress
icon: https://sorry-cypress.dev/__assets__/icon.png
maintainers:
  - name: tico24
    url: https://crumbhole.com
dependencies:
  - name: minio
    repository: https://helm.min.io/
    version: 8.0.9
    condition: minio.enabled
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 10.19.0
    condition: mongodb.internal_db.enabled
